# Generated by Django 4.0.4 on 2022-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0002_entry_listofentries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='age',
        ),
        migrations.AddField(
            model_name='entry',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='entry',
            name='date_of_death',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
